// <auto-generated />
using System;
using ASP_Exam.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ASP_Exam.Migrations
{
    [DbContext(typeof(ExamContext))]
    [Migration("20240125133531_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ASP_Exam.Data.Models.Materii", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid?>("ProfesoriId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ProfesoriId");

                    b.ToTable("Materii");
                });

            modelBuilder.Entity("ASP_Exam.Data.Models.Profesori", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Profesori");
                });

            modelBuilder.Entity("ASP_Exam.Data.Models.Materii", b =>
                {
                    b.HasOne("ASP_Exam.Data.Models.Profesori", null)
                        .WithMany("MateriiAsociate")
                        .HasForeignKey("ProfesoriId");
                });

            modelBuilder.Entity("ASP_Exam.Data.Models.Profesori", b =>
                {
                    b.Navigation("MateriiAsociate");
                });
#pragma warning restore 612, 618
        }
    }
}
